name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch bundled map images (optional)
        shell: bash
        run: |
          set -Eeuo pipefail
          mkdir -p public/maps
          fetch_into() {
            out="$1"; shift
            for url in "$@"; do
              echo "Trying $url -> $out"
              if curl -L --fail --silent --show-error "$url" -o "$out"; then
                echo "Fetched $out from $url"
                return 0
              fi
            done
            echo "No source available for $out (skipping)"
            return 0
          }
          # Dark basemap candidates (public-domain/CC BY-SA sources)
          fetch_into public/maps/world-dark-2048.jpg \
            "https://upload.wikimedia.org/wikipedia/commons/8/80/World_map_-_low_resolution.png" \
            "https://upload.wikimedia.org/wikipedia/commons/2/21/World_map_with_four_colours.svg" # fallback SVG as raster may fail
          # Boundaries overlay (transparent) candidates
          fetch_into public/maps/world-admin0-boundaries-2048.png \
            "https://upload.wikimedia.org/wikipedia/commons/4/4a/BlankMap-World_White.svg" \
            "https://upload.wikimedia.org/wikipedia/commons/8/80/World_map_-_low_resolution.png"
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
